# -*- coding: utf-8 -*-
"""Chatbot de Plantas com Streamlit para Colab Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqiRVPvaJS1MdcD3Esi_XQbd3fuuxnR_
"""

import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

from google import genai

client = genai.Client()

import google.generativeai as genai

model = "gemini-2.0-flash"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py


from pyngrok import ngrok

import subprocess
import time

# Inicia o Streamlit em um processo separado
process = subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"],
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)


